#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="vim"
# DMENUEDITOR="leafpad"
DMEDITOR="kitty -e nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(

"hyprland           $HOME/.config/hypr/hyprland.conf"
"awesome             $HOME/.config/awesome/rc.lua"
#"awesome_fp          $HOME/.config/awesome/themes/fp/theme.lua"
#"awesome_def         $HOME/.config/awesome/themes/my-default/theme.lua"
#"alacritty           $HOME/.config/alacritty/alacritty.toml"
"kitty               $HOME/.config/kitty/kitty.conf"
"zsh                 $HOME/.zshrc"
"nvim                $HOME/.config/nvim/init.vim"
"picom               $HOME/.config/picom/picom.conf"
"autoinstall.sh      $HOME/.dotfiles/autoinstall.sh"
"apps.md             $HOME/.dotfiles/all/apps.md"
"rofi-config         $HOME/.config/rofi/config.rasi"
"rofi-files          $HOME/.config/scripts/rofi/rofi-files"
"rofi-search         $HOME/.config/scripts/rofi/rofi-search"
#"4) bash - $HOME/.bashrc"
    "quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i  20 -p ' Editar ')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi
