#!/usr/bin/env bash
#
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu and a web browser
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining our web browser.
DMBROWSER="google-chrome"

# An array of search engines.  You can edit this list to add/remove
# search engines. The format must be: "engine_name - url".
# The url format must allow for the search keywords at the end of the url.
# For example: https://www.amazon.com/s?k=XXXX searches Amazon for 'XXXX'.
declare -a options=(
"google          https://www.google.com/search?q="
"translate       https://translate.google.com/?sl=auto&tl=en&text="
"symbolab        https://www.symbolab.com/solver/line-standard-form-calculator/"
"youtube         https://www.youtube.com/results?search_query="
"flatpak         https://flathub.org/apps/search?q="
"googleimages    https://www.google.com/search?hl=en&tbm=isch&q="
"drive           https://drive.google.com/drive/search?q="
"github          https://github.com/search?q="
#" gitlab        https://gitlab.com/search?search="
#" letterboxd    https://letterboxd.com/search/"
#" wikipedia     https://en.wikipedia.org/wiki/"
#" duckduckgo    https://duckduckgo.com/?q="
"quit"
)

# Picking a search engine.
while [ -z "$engine" ]; do
enginelist=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i 20 -p ' Search ') || exit
engineurl=$(echo "$enginelist" | awk '{print $NF}')
engine=$(echo "$enginelist" | awk '{print $1}')
done

# Searching the chosen engine.
while [ -z "$query" ]; do
query=$(rofi -dmenu -i 20 -p " $engine ") || exit
#query=$(rofi -dmenu -i 20 -p "Searching $engine: ") || exit
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query"

